### ISSUE TITLE
UI glitches with satchel

### ISSUE THREAD

**Issue by ghost** [wallstation13/wallstation13#174]
### Client Version:

515.1642

### Issue Summary:

On round 112, after picking up a regular cardboard box to hold my tools in, this happened:
![image](https://github.com/user-attachments/assets/8f1cfafb-3f1c-4794-b277-cd30059eff0b)

The icons for the backpack slot seemed to be missing their background, any new items I put in the backpack would not appear, and taking out items would not re-arrange the items. In order to access the new items that wouldn't appear, I had to dump the bag out (which was pretty nerve-racking because of all the tot items I had in it).
I managed to "fix" the bug myself by just getting a new backpack from a locker.
This might've just been an issue with my BYOND or it could be an upstream issue, not sure.

### Round ID:

112

### Test Merge Information:

#24

### Reproduction Steps:

I'm not sure if anyone else will be able to reproduce this because I think it might just be something on my end, but:
1. Pick up a cardboard box.
2. Put it in your backpack.
3. Open your backpack and see the fuckiness.

**Comment by GPeckman** [comment]
Upstream bug, see tgstation/tgstation#84507
