### ISSUE TITLE
medbots have a wallening offset

### ISSUE THREAD

**Issue by grungussuss** [wallstation13/wallstation13#72]
Reporting client version: 515.1641

## Issue Summary
![image](https://github.com/user-attachments/assets/b0b89565-29e5-4864-87a6-22473d7120c3)

## Round ID:
43

## Testmerges:
- [[tm only] Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://github.com/wallstation13/wallstation13/pull/24)

**Comment by GPeckman** [comment]
Can't reproduce locally on main.
![screenshot](https://github.com/user-attachments/assets/d7cd70bb-ea21-414b-afbc-593e45348bf5)
