### ISSUE TITLE
Old, bad, broken and insta death gateway was re-enabled on accident upon porting the server

### ISSUE THREAD

**Issue by Admiral-Gigaton** [wallstation13/wallstation13#88]
Reporting client version: 515.1642

## Issue Summary
A gateway which was never finished, fixed, or really done well, is back in rotation. in this gateway there is ZERO atmosphere, ZERO space suits or protection against this, and ZERO ways to get out upon entering.

## Round ID:
49

## Testmerges:
- [[tm only] Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://github.com/wallstation13/wallstation13/pull/24)

**Comment by grungussuss** [comment]
Disabling it until it's fixed

**Comment by MoffNyan** [comment]
The gateway is caves.dmm, there is an exit but it is incredibly difficult to get to and guarded by a LOT of skeleton mobs it looks like?
Would be nice if this gateway could get fixed up, particularly the atmosphere seemed broken which made everyone die to cold air and pressure (like in space).
I wonder if it would be feasible balance wise to give some additional gear to help the people who get in actually have a surviving chance? There does seem to be a story told within some slips of paper, and I love ruins that have stories, so it'd be cool to be able to give this ruin a chance.

I was told that there's also a lot of very strong loot within this ruin, including some magic books or something? Might be worth making sure there isn't anything that can cause excessive grief.

**Comment by mc-oofert** [comment]
oh christ isnt this the gateway with nukeop and wizard gear

**Comment by Yobrocharlie** [comment]
> Disabling it until it's fixed

Gateway has been tweaked nerfed and is ready to be added
https://github.com/wallstation13/wallstation13/pull/120

**Comment by Blacklist897** [comment]
This ruin is very old and fucking nuts, there are self recharging laser shotguns, necromantic stone, funny wizard hammer and a load of spell books

**Comment by Dawnseer** [comment]
Oh I remember this gateway. It even has a ghostrole skeleton spawn in there. Had a grand old journey trying to escape as the skellington.

**Comment by GPeckman** [comment]
Apparently fixed by #120
